### Get all shopping lists
GET http://localhost:8082/api/shopping-lists

### Put shopping list (User does not exist)
PUT http://localhost:8082/api/shopping-lists/c4804e0f-769e-4ab9-9ebe-0578fb4f0011
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "New list",
  "date": "2024-10-27T22:46:43.404Z",
  "status": "ACTIVE",
  "userId": "c4804e0f-769e-4ab9-9ebe-0578fb4f0011"
}

### Get shopping list by Id
GET http://localhost:8082/api/shopping-lists/c4804e0f-769e-4ab9-9ebe-0578fb4f0011

### Put shopping list
PUT http://localhost:8082/api/shopping-lists/c4804e0f-769e-4ab9-9ebe-0578fb4f0011
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "New list",
  "date": "2024-10-27T22:46:43.404Z",
  "status": "ACTIVE",
  "userId": "c4804e0f-769e-4ab9-9ebe-0578fb4f00a6"
}

### Get shopping list by Id
GET http://localhost:8082/api/shopping-lists/c4804e0f-769e-4ab9-9ebe-0578fb4f0011

### Get shopping lists by UserID
GET http://localhost:8082/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a8/shopping-lists

### Get shopping list by id
GET http://localhost:8082/api/shopping-lists/c4804e0f-769e-4ab9-9ebe-0578fb4f0011

### Get all shopping lists
GET http://localhost:8082/api/shopping-lists

### Delete shopping list
DELETE http://localhost:8082/api/shopping-lists/c4804e0f-769e-4ab9-9ebe-0578fb4f0011

### Get all shopping lists
GET http://localhost:8082/api/shopping-lists