### Get all products
GET http://localhost:8081/api/products

### Get all products by name
GET http://localhost:8081/api/products/name/Product5

### Put product (Shopping list does not exist)
PUT http://localhost:8081/api/products/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Milk",
  "category": "DRINKS",
  "price": 1.5,
  "quantity": 1,
  "isBought": false,
  "shoppingListId": "c4804e0f-769e-4ab9-9ebe-0578fb4f00a7"
}

### Put product
PUT http://localhost:8081/api/products/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Milk",
  "category": "DRINKS",
  "price": 1.5,
  "quantity": 1,
  "isBought": false,
  "shoppingListId": "c4804e0f-769e-4ab9-9ebe-0578fb4f00b1"
}

### Get products by shopping list id
GET http://localhost:8081/api/shopping-lists/c4804e0f-769e-4ab9-9ebe-0578fb4f00b1/products

### Get product by id
GET http://localhost:8081/api/products/c4804e0f-769e-4ab9-9ebe-0578fb4f00b6

### Delete product
DELETE http://localhost:8081/api/products/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76

### Get products by shopping list id
GET http://localhost:8081/api/shopping-lists/c4804e0f-769e-4ab9-9ebe-0578fb4f00b1/products
